---
config_home_dir: "/{{ 'Users' if ansible_os_family == 'Darwin' else 'home' }}/{{ config_user }}"
config_os_family: "{{ ansible_facts['os_family'] }}"
config_user: "{{ ansible_facts['user_id'] }}"
