---
- name: Config setup playbook
  hosts: "{{ targets | default('laptop') }}"
  become: "{{ switch_user | default(false) }}"
  vars_files:
    - "vars/{{ custom_vars_file | default('empty') }}.yaml"

  tasks:
    - name: Import auto/user vars
      ansible.builtin.include_vars:
        dir: "vars/auto/{{ config_user }}"
      failed_when: false

    - name: Import host/user vars
      ansible.builtin.include_vars:
        dir: "vars/host_vars/{{ config_user }}/{{ inventory_hostname }}"
      failed_when: false

    - name: Import group/user vars
      ansible.builtin.include_vars:
        dir: "vars/group_vars/{{ config_user }}/{{ item }}"
      loop: "{{ group_names }}"
      failed_when: false

    - name: Ensure required variables are defined
      ansible.builtin.assert:
        that:
          - git_name is defined
          - git_name is string
          - git_name | length > 0
      when: '"gitconfig" in task_list'

    - name: Find user's primary group
      block:
        - name: Lookup primary group
          ansible.builtin.command: "id -gn {{ config_user }}"
          changed_when: false
          register: output

        - name: Register group name
          ansible.builtin.set_fact:
            config_group: "{{ output.stdout }}"

    - name: Non-Windows tasks
      when: config_os_family != "Windows"
      block:
        - name: Linux Only tasks
          when: config_os_family != "Darwin"
          block:
            - name: Setup perltidy
              ansible.builtin.include_role:
                name: perltidy
              when: '"perltidy" in task_list'

            - name: Setup hyprland config
              ansible.builtin.include_role:
                name: hyprland
              when:
                - '"hyprland" in task_list'
                - use_hyprland | default(false)

            - name: Setup i3 config
              ansible.builtin.include_role:
                name: i3
              when:
                - '"i3" in task_list'
                - use_i3 | default(false)

            - name: Setup sway wm config
              ansible.builtin.include_role:
                name: sway
              when:
                - '"sway" in task_list'
                - use_sway | default(false)

            - name: Rescue this task if we cannot become
              when:
                - '"sysctl" in task_list'
                - use_sysctl | default(false)
              block:
                - name: Add sysctl.d files
                  ansible.builtin.include_role:
                    name: sysctl
              rescue:
                - name: Display rescue message
                  ansible.builtin.debug:
                    msg: "Unable to run sysctl tasks. Did you supply a become password?"
        - name: Setup bash profile
          ansible.builtin.include_role:
            name: bash
          when: '"bash" in task_list'

        - name: Add termcap files
          ansible.builtin.include_role:
            name: termcap
          when:
            - '"termcap" in task_list'
            - use_termcap | default(true)

        - name: Setup tmux config
          ansible.builtin.include_role:
            name: tmux
          when:
            - '"tmux" in task_list'
            - use_tmux | default(false)

        - name: Setup vim
          ansible.builtin.include_role:
            name: vim
          when: '"vim" in task_list'

    - name: Setup gitconfig
      ansible.builtin.include_role:
        name: gitconfig
      when: '"gitconfig" in task_list'

    - name: Setup ssh configs
      ansible.builtin.include_role:
        name: ssh
      when: '"ssh" in task_list'
