[project]
name = "configs"
version = "0.1.0"
description = "jdratlif/configs.git"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "ansible-core<2.17",
]

[dependency-groups]
dev = [
    "ansible-lint>=25.8.2",
]
