---
ssh_authorized_keys:
  - ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAICMpV1NruIlhslQT56n+Gzr63c55RcumQKUUAiZnYDTC

ssh_bastion_config: true

ssh_host_common_configs:
  ControlMaster: auto
  ControlPath: ~/.ssh/cp-%r@%h:%p
  ControlPersist: 5m

ssh_host_configs:
  jdratlif-dev8.bldc.grnoc.iu.edu:
    RemoteForward:
      - "1080 localhost:1080"
      - "1081 localhost:1081"
      - "1082 localhost:1082"
      - "1083 localhost:1083"
  jdratlif-dev8.ctc.grnoc.iu.edu:
    RemoteForward:
      - "1080 localhost:1080"
      - "1081 localhost:1081"
      - "1082 localhost:1082"
      - "1083 localhost:1083"

ssh_vscode_hosts:
  jdratlif-dev8.bldc.grnoc.iu.edu:
  jdratlif-dev8.ctc.grnoc.iu.edu:
  puppet7.grnoc.iu.edu:
  puppet.grnoc.iu.edu:
  puppet7.bldc.nwave.noaa.gov:
  puppet.bldc.nwave.noaa.gov:
