---
ssh_host_configs:
  jdratlif-dev8.grnoc.iu.edu:
    RemoteForward:
      - "*:1080 localhost:1080"
      - "*:1081 localhost:1081"
      - "*:1082 localhost:1082"
      - "*:1083 localhost:1083"
  jdratlif-dev8.ctc.grnoc.iu.edu:
    RemoteForward:
      - "*:1080 localhost:1080"
      - "*:1081 localhost:1081"
      - "*:1082 localhost:1082"
      - "*:1083 localhost:1083"
  araje-dev.grnoc.iu.edu:
    RemoteForward:
      - "*:1080 localhost:1080"
  xaiver:
    Hostname: xaiver.technoplaza.net
    Port: 5122
    DynamicForward: 1084
    LocalForward:
      - 13389 xaiver11:3389

ssh_vscode_hosts:
  jdratlif-dev8.grnoc.iu.edu:
  jdratlif-dev8.ctc.grnoc.iu.edu:
  puppet7.grnoc.iu.edu:
  araje-dev.grnoc.iu.edu:
  puppet7.bldc.nwave.noaa.gov:
