---
ssh_host_configs:
  jdratlif-dev8.grnoc.iu.edu:
    RemoteForward:
      - '*:1080 localhost:1080'
      - '*:1081 localhost:1081'
      - '*:1082 localhost:1082'
      - '*:1083 localhost:1083'
  xaiver:
    Hostname: xaiver.technoplaza.net
    Port: 5122
    DynamicForward: 1084
    LocalForward:
      - 13389 xaiver-pc:3389

ssh_vscode_hosts:
  jdratlif-dev8.grnoc.iu.edu:
    port: 10101
  puppet7.grnoc.iu.edu:
    port: 10102
  puppet7.bldc.nwave.noaa.gov:
    port: 10201
