---
- name: Block tag
  tags: [ssh]
  block:
    - name: Merge default values with overrides
      ansible.builtin.set_fact:
        ssh_host_common_configs: "{{ ssh_host_common_configs_defaults | combine(ssh_host_common_configs, recursive=True) }}"

    - name: Make ssh config directory
      ansible.builtin.file:
        path: "{{ config_home_dir }}/.ssh"
        state: directory
        owner: "{{ config_user }}"
        group: "{{ config_group }}"
        mode: "0700"

    - name: Setup ssh authorized_keys file
      ansible.builtin.template:
        src: authorized_keys.j2
        dest: "{{ config_home_dir }}/.ssh/authorized_keys"
        owner: "{{ config_user }}"
        group: "{{ config_group }}"
        mode: "0600"
      when: ssh_authorized_keys | length > 0

    - name: Remove authorized keys file
      ansible.builtin.file:
        path: "{{ config_home_dir }}/.ssh/authorized_keys"
        state: absent
      when: ssh_authorized_keys | length == 0

    - name: Setup ssh config file
      ansible.builtin.template:
        src: ssh_config.j2
        backup: true
        dest: "{{ config_home_dir }}/.ssh/config"
        owner: "{{ config_user }}"
        group: "{{ config_group }}"
        mode: "0600"
