---
all:
  children:
    niri:
      hosts:
        beelink:
        docker:
        pangolin16:
        yoga4:
    work:
      hosts:
        beelink:
        docker:
        pangolin16:
        yoga4:

  hosts:
    beelink:
    docker:
      ansible_host: host.docker.internal
    pangolin16:
    yoga4:

  vars:
    ansible_user: jdratlif
