# Generated by Anaconda 42.27.12
# Generated by pykickstart v3.62
#version=DEVEL

# Keyboard layouts
keyboard --vckeymap=us --xlayouts='us'
# System language
lang en_US.UTF-8

# Network information
network  --bootproto=dhcp --device=link --ipv6=auto --activate
network  --hostname=yoga4

%packages
# base install
@core
python3-dnf
python3-libdnf5
%end

ignoredisk --only-use=nvme0n1
autopart --encrypted --passphrase=kickstart
clearpart --all --initlabel
zerombr

# System timezone
timezone America/Indiana/Indianapolis --utc

#Root password
rootpw --lock
user --groups=wheel --name=jdratlif --password=$y$j9T$gv50Aap6/sDY41kfaRXe6bhV$QST9BTAaiN5yl.YgBmQDYEAoLjzrNJCvFbM69BfU2U7 --iscrypted --gecos="John Ratliff"
