---
- name: Config setup playbook
  hosts: "{{ targets }}"
  vars:
    targets: laptop
  tasks:
    - name: Run always tasks
      ansible.builtin.import_tasks: tasks/push/always.yml
      tags: [always]

    - name: Setup gitconfig
      ansible.builtin.import_role:
        name: jdratlif.configs.gitconfig
      tags: [git]

    - name: Setup ssh configs
      ansible.builtin.import_role:
        name: jdratlif.configs.ssh
      tags: [ssh]

    - name: Run unix tasks
      ansible.builtin.import_tasks: tasks/push/unix.yml
      tags: [unix]
