---
bash_aliases: {}
bash_exports: {}
bash_functions: {}
bash_path_pre: []
bash_path_post: []
bash_ssh_agent: false
bash_sources: []

bash_custom_prompt: true
bash_custom_my_prompt: false

bash_editor: vim

bash_history_options: "{{ bash_history_options_zsh if bash_zsh else bash_history_options_bash }}"

bash_history_time_format: "[%F %T] "
bash_history_size: 10000
bash_history_file_size: 10000

bash_rc_file: "{{ '.zshrc' if bash_zsh else '.bashrc' }}"

bash_pager: less -X

bash_zsh: "{{ true if config_os_family == 'Darwin' else false }}"
